import type { InitDataType } from "./types";

export const initData: InitDataType = {
  boards: [
    {
      id: crypto.randomUUID(),
      title: "Today's Work",
      progress: ["Todo", "Done"],
      tasks: [
        {
          id: crypto.randomUUID(),
          title: "Reply to all unanswered Emails and Teams messages",
          desc: "also don't forget to check both private and public emails for new emails",
          due: new Date(),
          progress: "Todo",
        },
        {
          id: crypto.randomUUID(),
          title: "Prepare all resources for the scheduled meeting ",
          desc: "",
          due: new Date(),
          progress: "Todo",
        },
        {
          id: crypto.randomUUID(),
          title: "Draft summary report for weekly team progress",
          desc: "Include key metrics, blockers, and next steps for each team member",
          due: new Date(),
          progress: "Todo",
        },
        {
          id: crypto.randomUUID(),
          title: "Follow up with IT on access requests for new hires",
          desc: "Ensure all required systems and tools are provisioned",
          due: new Date(),
          progress: "Done",
        },
        {
          id: crypto.randomUUID(),
          title: "Schedule one-on-one meetings with team members",
          desc: "Plan check-ins for the upcoming week and confirm availability",
          due: new Date(),
          progress: "Done",
        },
        {
          id: crypto.randomUUID(),
          title: "Review and approve pending project documents",
          desc: "Check version control, formatting, and compliance requirements",
          due: new Date(),
          progress: "Done",
        },
      ],
    },
    {
      id: crypto.randomUUID(),
      title: "House Work",
      progress: ["Todo", "Done"],
      tasks: [
        {
          id: crypto.randomUUID(),
          title: "Relentlessly hunt down mosquitoes 🦟",
          desc: "bezzzzz 🦟🦟🦟",
          due: null,
          progress: "Todo",
        },
        {
          id: crypto.randomUUID(),
          title: "Investigate mysterious fridge smells 🕵️‍♂️",
          desc: "I think its the left over pizza 🕵️‍♂️",
          due: null,
          progress: "Todo",
        },
        {
          id: crypto.randomUUID(),
          title: "Reunite lonely socks with their partners 🧦",
          desc: "double check the washer and under the bed for 🧦",
          due: null,
          progress: "Todo",
        },
        {
          id: crypto.randomUUID(),
          title: "Clean the tub so you can cry in peace 🛁",
          desc: "🛁",
          due: null,
          progress: "Done",
        },
        {
          id: crypto.randomUUID(),
          title: "Rescue leftovers from the back of the fridge 🧊",
          desc: "",
          due: null,
          progress: "Done",
        },
        {
          id: crypto.randomUUID(),
          title: "Clean windows until birds try to fly through them 🐦",
          desc: "",
          due: null,
          progress: "Done",
        },
      ],
    },
    {
      id: crypto.randomUUID(),
      title: "Trip to Santorini",
      progress: ["Urgent", "Important", "Later"],
      tasks: [
        {
          id: crypto.randomUUID(),
          title: "Estimate overall travel budget",
          desc: "Include transport, meals, tours, and a small buffer",
          due: null,
          progress: "Urgent",
        },
        {
          id: crypto.randomUUID(),
          title: "List must‑see landmarks",
          desc: "Akrotiri ruins, Red Beach, Caldera trail, Ammoudi Bay sunset",
          due: null,
          progress: "Urgent",
        },
        {
          id: crypto.randomUUID(),
          title: "Prepare packing checklist",
          desc: "Light clothing, swimwear, hat, sunscreen, EU power adapter",
          due: null,
          progress: "Urgent",
        },
        {
          id: crypto.randomUUID(),
          title: "Research ferry schedules  to Santorini",
          desc: "Compare Blue Star vs. SeaJets timings and prices",
          due: null,
          progress: "Important",
        },
        {
          id: crypto.randomUUID(),
          title:
            "Compare accommodation options in Santorini and nearby islands",
          desc: "Look at reviews, availability, and cancellation policies",
          due: null,
          progress: "Important",
        },
        {
          id: crypto.randomUUID(),
          title: "Coordinate time‑off approval with manager",
          desc: "Submit formal leave request in HR portal",
          due: null,
          progress: "Important",
        },
        {
          id: crypto.randomUUID(),
          title: "Review 10‑day weather forecast",
          desc: "Adjust activities and packing list if heatwave predicted",
          due: null,
          progress: "Later",
        },
        {
          id: crypto.randomUUID(),
          title: "Purchase travel insurance",
          desc: "Comprehensive plan with medical coverage",
          due: null,
          progress: "Later",
        },
        {
          id: crypto.randomUUID(),
          title: "Set travel notice on bank cards",
          desc: "Activated for Greece and transit countries",
          due: null,
          progress: "Later",
        },
      ],
    },
  ],
};
